### ISSUE TITLE
dnfmodule fails to enable module with ensure version and no default stream

### ISSUE THREAD

**Issue by evgeni** [puppetlabs/puppet#9142]
## Describe the Bug

the old code would work correctly for `ensure => present`, but not for `ensure => 'some_stream'`, as dnf does include the whole module spec in the error message and the old regex didn't match anymore.

```
# dnf module install -d 0 -e 1 -y 389-ds
Error: Problems in request:
broken groups or modules: 389-ds

# dnf module install -d 0 -e 1 -y 389-ds:1.4
Error: Problems in request:
broken groups or modules: 389-ds:1.4
```

## Expected Behavior
module is correctly enabled by switching to the "enable only" codepath automatically 

## Steps to Reproduce
```puppet
package { '389-ds':
  ensure => '1.4',
  provider => dnfmodule,
}
```

## Environment
 - Version 7.26
 - Platform CentOS Stream 8

## Additional Context
Setting `enable_only => true` avoids the issue, but the code should be able to figure this out itself.
See https://github.com/voxpupuli/puppet-nodejs/pull/488

**Comment by joshcooper** [comment]
Fixed in #9138
