### ISSUE TITLE
Missing Puppet packages for Debian 12 (Bookworm)

### ISSUE THREAD

**Issue by sysbeekeeper** [puppetlabs/puppet#9149]
Hello,

Debian 12 (Bookworm) stable release was published in July 2023, however there are still no Puppet packages released at https://apt.puppetlabs.com/ or https://nightlies.puppet.com/apt/index.html (I'm referring to Puppetserver, Puppet Agent, PDK, and Bolt packages).

While Debian 12 ships their packages for Puppet 7, but it would be beneficial for all Debian users to have Puppet 8 available from the official Puppetlabs APT repository.

Other's have [asked the same questions](https://groups.google.com/g/puppet-users/c/vlGQ8I9aBQg) a while back, but no updates were provided about Debian 12 packages so far.

Cheers!

**Comment by kenyon** [comment]
This is https://puppet.atlassian.net/browse/PA-4995.

**Comment by tlundse** [comment]
The JIRA referenced above is still unassigned and is attached to a project that seems to have been archived. I note that this github issue is also unassigned.

I would also like to have official puppetlabs debian packages for bookworm on apt.puppetlabs.com

**Comment by smortex** [comment]
@tlundse (and all other interested in this), quoting @joshcooper on Slack:

> Debian 12 is nearly ready to ship nightly! It won't make the Jan release, but hopefully soon after

So we can check https://nightlies.puppet.com/apt/pool/index.html from time to time to see when a `bookworm` directory appear and give it a try.

**Comment by joshcooper** [comment]
Nightly builds for Intel and ARM are available! See https://puppetcommunity.slack.com/archives/C0W298S9G/p1707732307088589

**Comment by joshcooper** [comment]
Packages were released in https://www.puppet.com/docs/puppet/7/release_notes_puppet.html#enhancements_puppet_x-7-29-0 and https://www.puppet.com/docs/puppet/8/release_notes_puppet.html#enhancements_puppet_x-8-5-0

**Comment by smortex** [comment]
@joshcooper I was feeling that this issue would serve as a meta-issue for the whole Puppet stack, and not only for the Puppet-Agent.

Should we open similar issues on the https://github.com/puppetlabs/puppetserver / https://github.com/puppetlabs/puppetdb repositories, or re-open this one until all these Debian 12 packages are available?

**Comment by joshcooper** [comment]
@smortex unfortunately different teams own server, db, bolt, pdk so I think separate issues are needed
