### ISSUE TITLE
Wrong service provider selected for Raspberry Pi OS (raspbian) 12 bookworm

### ISSUE THREAD

**Issue by jaevans** [puppetlabs/puppet#9169]
## Describe the Bug
When running puppet agent provided with Raspberry Pi OS, the message "Warning: Found multiple default providers for service: init, systemd; using init". This causes some services such as `firewalld` to be unmanageable.

## Expected Behavior
Puppet uses the correct Service provider, `systemd`

## Steps to Reproduce
1. Install Raspberry Pi OS Bookworm
2. Install `puppet` package
3. Run `puppet agent -t`

## Environment
 - Version  7.23.0
 - Platform Raspberry Pi OS 12 (bookworm)

## Additional Context
I don't know enough about Debian to know if this is the case in all Debian platforms.

**Comment by mhashizume** [comment]
We are also tracking this internally as PUP-11949

**Comment by Adawntoremember** [comment]
> ## Describe the Bug
> When running puppet agent provided with Raspberry Pi OS, the message "Warning: Found multiple default providers for service: init, systemd; using init". This causes some services such as `firewalld` to be unmanageable.
> 
> ## Expected Behavior
> Puppet uses the correct Service provider, `systemd`
> 
> ## Steps to Reproduce
> 1. Install Raspberry Pi OS Bookworm
> 2. Install `puppet` package
> 3. Run `puppet agent -t`
> 
> ## Environment
>  - Version  7.23.0
>  - Platform Raspberry Pi OS 12 (bookworm)
> 
> ## Additional Context
> I don't know enough about Debian to know if this is the case in all Debian platforms.

**Comment by fabieins** [comment]
Is it possible to change the selected default to `systemd`, when `init` and `systemd` where found?
We have the same problem with Pop!_OS 22.04
