### ISSUE TITLE
Bug: puppet-agent 8.2.0 on gentoo not detecting active init

### ISSUE THREAD

**Issue by binford2k** [puppetlabs/puppet#9182]
### Discussed in https://github.com/puppetlabs/community/discussions/51

<div type='discussions-op-text'>

<sup>Originally posted by **samuraiii** December  2, 2023</sup>
Hi all,
there is a regression for puppet-agent on gentoo linux, presumably between versions >8 and 8<=.
The 7.X version was detecting two inits on my box but was choosing the right every time (systemd).
Version 8.2.0 detects also both inits but chooses the "init" one, which breaks all systemd related facts.

I am not sure where to post this since tickets are obsolete, so I am sorry for possible misposting.
Cheers
S</div>

**Comment by joshcooper** [comment]
@samuraiii can you provide the output of `puppet agent -td` for both a working example and a non-working case? Also note we merged some changes recently for gentoo in e007a70469c39d4bb50311cb5ab34129cf6d4f22, but it hasn't been released yet. You might try installing a nightly puppet gem from https://nightlies.puppet.com/downloads/gems/puppet8-nightly/index.html to see if it resolves the issue

**Comment by samuraiii** [comment]
puppet 7.24.0 log is located here:
https://gist.github.com/samuraiii/40443cadc0803855b69febd1e1d319cb

and puppet 8.3.1 here:
https://gist.github.com/samuraiii/de56648a6055d1a531a1cb6cf377c67d

I might try the gem, but not any time soon...
I have never done this before and I do not have time to research it right now.

**Comment by joshcooper** [comment]
@samuraiii I think the behavior change is because before @bastelfreak change, gentoo didn't have a default service provider. In the upcoming 8.x release, only `systemd` should be the default, so I'm going to mark this as a dup of PUP-11593
