### ISSUE TITLE
Drop Ruby 2.5 in Puppet 7

### ISSUE THREAD

**Issue by jordanbreen28** [puppetlabs/puppet#9189]
## Use Case
The gemspec still requires a minimum ruby version of 2.5 [here](https://github.com/puppetlabs/puppet/blob/4d6791aac08410637720a108399b51ccf31a3498/.gemspec#L21).

## Describe the Solution You Would Like
Raise minimum ruby requirement to ruby 2.6 (which I believe is needed for puppet server). Will help keep consistency with other tooling and modules in the puppet ecosystem.

**Comment by joshcooper** [comment]
@jordanbreen28 we raised the minimum version to 3.1 in puppet8 https://github.com/puppetlabs/puppet/pull/9048.

Are you asking to update the minimum to ruby 2.6 for puppet7?

**Comment by joshcooper** [comment]
Confirmed with @jordanbreen28 this is was for 7.x https://github.com/puppetlabs/puppet/blob/4d6791aac08410637720a108399b51ccf31a3498/.gemspec#L21 and is related to https://github.com/puppetlabs/puppet-resource_api/pull/335

**Comment by joshcooper** [comment]
@jordanbreen28 now that PE 2021.7.x is in overlap support https://www.puppet.com/docs/pe/2021.7/release_notes_pe#release_notes_pe_x-y-9, puppet 7 will only receive fixes for security updates, high priority bugs and changes needed for releases. As such, I'm going to close this as won't do. Please let me know if I've mischaracterized the issue.
