### ISSUE TITLE
Missing puppet_gem binary on the Puppet7 bookworm package

### ISSUE THREAD

**Issue by guikolt** [puppetlabs/puppet#9201]
Puppet7-agent package for bookworm is maintained by Debian, I know. Still, the puppet_gem provider on the package is calling `/opt/puppetlabs/puppet/bin/gem` binary which doesn't exist in this package.

Except for bookworm, we had three different gem options: gem (_system_ provider), puppet_gem (provider) and puppetserver_gem (provider/module). Looks like the p7 package from debian is missing the puppet_gem provider as it only installs /usr/bin/gem which is the system provider.

## Describe the Bug
Calling the puppet_gem provider on the puppet7 agent installation from Bookworm breaks because there is no `/opt/puppetlabs/puppet/bin` directory on the debian package

## Expected Behavior
Puppet should call the correct (?) gem binary.

## Steps to Reproduce
1. Install the puppet7 package on bookworm
2. grep puppetlabs /usr/lib/ruby/vendor_ruby/puppet/provider/package/puppet_gem.rb
3. Notice that the puppet_gem provider is pointing to a gem file on a directory that doesn't exist
4. Installing gems using the puppet_gem provider will fail due to this

## Environment
 - puppet-agent 7.23.0-1
 - debian 12 (bookworm)

**Comment by joshcooper** [comment]
Hi @guikolt this is a bug in the Debian packages. They shouldn't include the `puppet_gem` provider or they should update the path to the `gem` binary so it's the same as the `gem` provider.

@ekohl has a PR to centralize some of these paths to make it easier for maintainers https://github.com/puppetlabs/puppet/pull/8938/files#diff-0b10c2b14f1d274d9a9a8d30f77b110c08c0fe2ee6b0d1bccb9cf1eb9b7e8706

Separately, we are working on official Debian 12 packages, which is being tracked in https://github.com/puppetlabs/puppet/issues/9149

Given these things I'm going to close this.
