### ISSUE TITLE
puppet 7.29.0 and 8.5.0 sink my arithmetic battleship!

### ISSUE THREAD

**Issue by jhoblitt** [puppetlabs/puppet#9268]
## Describe the Bug

Using a negative value with the Integer type assertion on a class causes a rather surprising pops error.

Example code which triggers the error:
```puppet
  Integer[-1] $slowlog_log_slower_than                           = 10000,
```
from

https://github.com/voxpupuli/puppet-redis/blob/e8ca35a403653a2dac60dd93afd33cca4f9c2d2e/manifests/init.pp#L432

causes

```
       error during compilation: The parameter '$slowlog_log_slower_than' must be a literal type, not a Puppet::Pops::Model::AccessExpression (file: /home/jhoblitt/github/lsst-control/spec/fixtures/modules/redis/manifests/init.pp, line: 432, column: 15) on node foreman.cp.lsst.org
```

## Expected Behavior

I expect my battleship to float!

## Steps to Reproduce
1. configure CI with a pessimistic version constraint which allows 7.29.0
2. have code which uses `Integer[<a filthy no good negative integer>]`
3. run ci

## Environment
 - Version 7.29.0
 - gha ubuntu latest runner

**Comment by kajinamit** [comment]
I also hit the same problem triggered by some definitions in puppet-rabbitmq ( https://github.com/voxpupuli/puppet-rabbitmq/blob/2605e305cc730f77fbb41c76a763cb471f7d66ce/manifests/init.pp#L435-L436 ), in our CI jobs which now uses `puppet-agent-7.29.0-1.el9.x86_64` and CentOS 9 Stream.

**Comment by fetzerms** [comment]
Just for the sake of completeness, as the title only refers to 7.29.0: This also fails on 8.5.0 (seen with rabbitmq and dhcp modules)

**Comment by bk-lg** [comment]
Sry for commenting in this allready closed issue but does someone else experience this behaviour with agent 7.23 and server 7.16?
As far as I understand only agents with version 7.29.0 should be impacted but i can observice the problematic behaviour on many hosts with an agent <7.29.0.

**Comment by seqizz** [comment]
> Just 2 cents, I had to remove cache folder on the master in order to make it work after downgrade to agent's 7.28

**Comment by bk-lg** [comment]
For everyone having the same issue. If your puppet agent on your puppetserver is 7.29 this seems to impact all other agents connection to this master. Downgrade the package, clear the cache and reboot server. After that it works again.
@seqizz thank you for mentioning the cache folder!

**Comment by kajinamit** [comment]
May I know any update (especially ETA of the fixed version) about this problem ?

I can't access the jira ticket (maybe I need to request access ? I used to have a different account but lost access to it when I leave my prev. company)

**Comment by fetzerms** [comment]
> For everyone having the same issue. If your puppet agent on your puppetserver is 7.29 this seems to impact all other agents connection to this master. Downgrade the package, clear the cache and reboot server. After that it works again. @seqizz thank you for mentioning the cache folder!

As 8.5.1 agent is out now, I only needed to restart the puppetmaster (8.5.0) in order to have it fix the error.
