### ISSUE TITLE
Ubuntu 24.04 packages

### ISSUE THREAD

**Issue by bastelfreak** [puppetlabs/puppet#9332]
## Use Case

Hi, Ubuntu 24.04 is the latest stable release. Please provide packages for it.

**Comment by mhashizume** [comment]
Hi @bastelfreak , thanks for filing this issue. This is in the queue for new OS additions

**Comment by couloum** [comment]
Hello. Do you have any ETA on when this will be available? Thank you

**Comment by sanchirico** [comment]
The official Puppet open source docs state "puppet-agent packages are available for these platforms."....Ubuntu 24.04 https://www.puppet.com/docs/puppet/8/system_requirements#supported_operating_systems-packaged-platforms

Yet apt.puppet.com still has no package for "noble"

Is there an alternative way to install for the time being?

**Comment by tdb** [comment]
It's not even in nightlies yet, as far as I can see. I've had no trouble installing the 22.04 package as a stop-gap solution. There's also the version packaged with Ubuntu, but things are in different places.

**Comment by couloum** [comment]
Hello. Is there any news for this package? For Ubuntu 22.04 we had to wait August to get the packages in the official repository. I was hopping that the wait could be shorted this time.
Thank you

**Comment by joshcooper** [comment]
We hope to have nightly puppet-agent packages for Ubuntu 24.04 x86_64 and ARM available next week, with GA in late July.

@sanchirico I filed https://github.com/puppetlabs/puppet-docs/issues/1156 to update the supported agent platforms. Feel free to comment on there with any corrections.

**Comment by joshcooper** [comment]
Nightly builds are now available for Ubuntu 24.04 arm and x86_64 https://nightlies.puppet.com/apt/index.html 

They'll be released in late July in the next set of platform releases. Give them a try and let us know if you have any issues.

**Comment by bastelfreak** [comment]
@joshcooper thanks a lot! Do you have estimates for puppetserver/puppetdb packages?

**Comment by joshcooper** [comment]
> Do you have estimates for puppetserver/puppetdb packages?

Sorry, I don't, that's handled by a different team.

**Comment by joshcooper** [comment]
Agent packages shipped in 7.32.1 and 8.8.1 so I'm going to going this. For example, https://www.puppet.com/docs/puppet/7/release_notes_puppet.html#release_notes_puppet_x-7-32-1

**Comment by bastelfreak** [comment]
> Sorry, I don't, that's handled by a different team.

@joshcooper can you tell me who is responsible for PuppetDB/Puppetserver releases / who we can ask?
