### ISSUE TITLE
Hiera example (https://github.com/puppetlabs/puppet/tree/main/examples/hiera) seriously out of date

### ISSUE THREAD

**Issue by spotter-puppet** [puppetlabs/puppet#9340]
This could potentially be considered more of a documentation bug, but it is part of the code, not the docs...).
The examples in the hoera section (https://github.com/puppetlabs/puppet/tree/main/examples/hiera) are significantly out of date, referring to hiera3 syntax.

**Comment by joshcooper** [comment]
@spotter-puppet Yes good point. It was last updated 11 years ago. Would you be willing to submit a PR to update them?

**Comment by mhashizume** [comment]
Updated in #9347
