### ISSUE TITLE
Missing `puppet-agent` packages in debian bookworm's `puppet` repository

### ISSUE THREAD

**Issue by smortex** [puppetlabs/puppet#9370]
## Describe the Bug

* The `puppet7` repo has Puppet 7 packages: https://apt.puppet.com/pool/bookworm/puppet7/p/puppet-agent/index.html
* The `puppet8` repo has Puppet 8 packages: https://apt.puppet.com/pool/bookworm/puppet8/p/puppet-agent/index.html
* The `puppet` repo has no Puppet packages: https://apt.puppet.com/pool/bookworm/puppet/p/

When installing the Puppet Agent using puppetlabs-puppet_agent module on a Debian 12 node without setting explicitly a collection, the `puppet` repo is installed, and as it contain no puppet-agent package, the [package from the distro](https://packages.debian.org/bookworm/puppet-agent) is installed.

## Expected Behavior

Same behavior as the other Debian versions: the `puppet` repository install Puppet 7 as it is still the default, and at some point will switch to Puppet 8.

## Steps to Reproduce

```
bolt task run puppet_agent::install -t root@some-new-debian-12-system
```

## Environment
 - Version n/a
 - Platform Debian 12 (bookworm)

Cc @neomilium

**Comment by joshcooper** [comment]
Thanks for letting us know @smortex, the release team is looking into it.

**Comment by mhashizume** [comment]
Our release team has fixed this issue, can you confirm @smortex ?

**Comment by smortex** [comment]
Looks good, thanks!
