### ISSUE TITLE
https://forgeapi.puppet.com/private/versions/puppet-agent is outdated

### ISSUE THREAD

**Issue by bastelfreak** [puppetlabs/puppet#9395]
## Describe the Bug

rspec-puppet-facts pull in `https://forgeapi.puppet.com/private/versions/puppet-agent` after each new puppet/facter release. The file is used within rspec-puppet unit tests to determine the correct facter version in relation to the specified puppet version (then the facter version is used to get the correct factset from facterdb). The latest 8.x entry is 8.3.1, latest 7.x is 7.27.0. Please update the file

## Expected Behavior

A parseable overview of components in recent Puppet releases.

## Steps to Reproduce
* `curl --silent https://forgeapi.puppet.com/private/versions/puppet-agent | jq .`

## Additional Context
* https://github.com/voxpupuli/rspec-puppet-facts/commit/290d5e6948c35aa3614849c8917241b7b4b8961f
* https://github.com/voxpupuli/rspec-puppet-facts/blob/master/lib/rspec-puppet-facts.rb#L390-L424

**Comment by smortex** [comment]
Oh! I wasn't aware of this API and I guess I could rely on it to make it easier for me to handle the FreeBSD packages (replacing [this *tedious* manual state](https://cgit.freebsd.org/ports/tree/sysutils/puppet8/Makefile#n43) with another *simpler* one).

**Comment by cthorn42** [comment]
For reference, https://github.com/puppetlabs/puppet-forge-api/blob/main/app/static/puppet_agent_components.json, looks to be the source of truth. That was being updated through 2022 by automation and stopped at some point. There was a manual update at one point in 2023 and nothing since then.
I think we can for sure push up a manual update, but better yet would be figuring out what happened with the automation around this.

**Comment by bastelfreak** [comment]
@cthorn42 can you do the manual release and let me know when the updated file is available? I can afterwards make a new release for rspec-puppet-facts.

**Comment by cthorn42** [comment]
My commit that added the `8.7.0` release to that private file was merged last week but I'm not seeing a change in the `https://forgeapi.puppet.com/private/versions/puppet-agent`.  I was hoping for a quick fix but that isn't the case, I will need to get some help from someone on the Forge to figure out what else needs done.

**Comment by bastelfreak** [comment]
now with the 8.8.1 release the file is outdated again.

**Comment by AriaXLi** [comment]
Hi @bastelfreak thanks for opening this issue! I've updated our internal documentation to make sure we manually update [https://github.com/puppetlabs/puppet-forge-api/blob/main/app/static/puppet_agent_components.json](https://github.com/puppetlabs/puppet-forge-api/blob/main/app/static/puppet_agent_components.json) so we hopefully won't run into this again so I'll close out this issue now.
