### ISSUE TITLE
Puppet 8.7.0 release archive is missing on downloads.puppet.com

### ISSUE THREAD

**Issue by bastelfreak** [puppetlabs/puppet#9411]
## Describe the Bug

At Gentoo we use the official .tar.gz releases from https://downloads.puppet.com/puppet/index.html to build Puppet. For example https://downloads.puppetlabs.com/puppet/puppet-8.6.0.tar.gz. For the 8.7.0 release, the archive is missing: https://downloads.puppetlabs.com/puppet/puppet-8.7.0.tar.gz

## Expected Behavior

https://downloads.puppetlabs.com/puppet/puppet-8.7.0.tar.gz should exist

## Steps to Reproduce

* `curl -iv https://downloads.puppetlabs.com/puppet/puppet-8.7.0.tar.gz`

## Environment
 - Version [e.g. 1.27.0]
 - Platform [e.g. Ubuntu 18.04]

## Additional Context

I'm sure this isn't the correct place to report this, but I also don't know which place is correct.

**Comment by cthorn42** [comment]
@bastelfreak thanks for the report, as for the place to report this is a good starting point as any. I'm not quite sure what generates that but I'll work with our RE team to figure this out.

**Comment by cthorn42** [comment]
The release team has pushed up the release archive for 8.7.0 and 7.31.0. I think a bit more work needs to be done to understand why those archives weren't shipped. But that work can is being tracked internally, this I believe we're good to close out.
