### ISSUE TITLE
only first name server attempted in finding the puppet server

### ISSUE THREAD

**Issue by rtprio** [puppetlabs/puppet#9450]
## Describe the Bug
I recently noticed all my puppet agents were failing when the primary DNS resolver was out. This was on FreeBSD.

## Expected Behavior
I would expect that puppet would use the next nameserver in the list to look up the address of the puppet server.

## Steps to Reproduce
1. Configure a host with two resolvers, the first one nonfunctional
2. Run the agent, I used `puppet agent -t -v --logdest console`
3. observe an error similar to the following

`puppet-agent[29201]: Could not retrieve catalog from remote server: Host is down - sendto(2) for "10.0.17.2" port 53 `

## Environment
 - Version 8.7.0
 - Platform FreeBSD 14.1

**Comment by joshcooper** [comment]
@rtprio can you provide more details about how you configured a "host with two resolvers, the first one nonfunctional"?

**Comment by rtprio** [comment]
sure thing; 

the resolv.conf of the host was like this:
```
nameserver 10.0.17.2
nameserver 10.0.17.4
```

In this case, .2 crashed and was no longer answering DNS. These hosts only have ipv4 at the moment, I have not tested the ipv6 side of this condition.

**Comment by rtprio** [comment]
I suppose I should have investigated deeper when it was happening; It seems to be properly using the next nameserver now. 🤷

**Comment by joshcooper** [comment]
Thanks for letting us know. I'm going to close this, but if you can reproduce feel free to reopen.
