### ISSUE TITLE
puppetserver error: cannot load such file -- puppetserver/ca/cli (LoadError)

### ISSUE THREAD

**Issue by banafshehft** [puppetlabs/puppet#9452]
## Describe the Bug
i can not run any puppetserver command becasue of this : 

```
sudo puppetserver ca list --all
[sudo] password for bani: 
<internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require': cannot load such file -- puppetserver/ca/cli (LoadError)
        from <internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
        from /opt/puppetlabs/server/apps/puppetserver/cli/apps/ca:3:in `<main>'
```

## Expected Behavior
i can run puppetserver 

## Environment
 - puppet server Version: 8.6.0-1
-puppet version: 7.32.1-3
 - Platform : archlinux : 6.10.5.arch1-1

## Additional Context
if you need any more info please let me know

**Comment by bastelfreak** [comment]
your problem is that you're mixing puppet agent 7 and puppetserver 8. Both need to have the same major version.

**Comment by banafshehft** [comment]
actually i could fix it by rebuilding the package . it seems now its using new ruby. i will close the ticket since the original issue resolved
