### ISSUE TITLE
fedora 41 repo

### ISSUE THREAD

**Issue by Stricken1670** [puppetlabs/puppet#9512]
Since the new build system is much more flexible and fedora 41 has been released yesterday, I kindly request adding fedora 41 support. I bet that the fedora-3* releases can be removed since they are ancient releases.

**Comment by bbkz** [comment]
the puppet agent doesn't work on fedora 41 because of #9506.

**Comment by Stricken1670** [comment]
I'm aware of the that problem, which is trivial to fix.
Your statement is untrue though, `puppet agent` works fine, even though you might not be able to install packages.

**Comment by bbkz** [comment]
Oh. yes sorry. you are right... i was just thinking about my use case.

**Comment by cthorn42** [comment]
@Stricken1670 thank you for the enhancement request for Fedora41. Taking a look at our backlog I don't think it is likely that we'll get around to adding support for the puppet-agent for Fedora-41.

**Comment by Stricken1670** [comment]
Fedora is always the current release and test bed for Red Hat releases. The puppet build environment has been updated to facilitate easy releases. All that is expected is to bump to the next releases and discard the old releases.

Thanks for taking your community seriously.

**Comment by Stricken1670** [comment]
Dear @mhashizume
In this ticket https://github.com/puppetlabs/puppet/issues/9320 you have stated you made the build process a lot easier.

Would you be able to generate a fedora 41 package? Ideally also whilst taking these PRs in account? https://github.com/puppetlabs/puppet/issues/9506

Thanks for your consideration.
